name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | base64 --decode > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem  # Set proper permissions for the key

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /path/to/your/project
            git pull origin main
            npm install
            npm run build
            pm2 restart node-app  # Assuming you are using PM2 to manage your app
          EOF
